name: "TimedMessages"
main: at.saith.twasi.TimedMessagesPlugin
version: 1.0
description:  "Adds timers to your stream."
author: Saith
dependencies:
  - Commands
  - StreamTracker
commands:
  - timer

permissions:
  - timer.add
  - timer.delete
  - timer.list
  - timer.enable
  - timer.disable

api: |
  type TimedMessages {
    listTimers: [Timer],
    registerTimer(command: String, interval: Int, enabled: Boolean): Timer,
    removeTimer(command: String): Timer,
    enableTimer(command: String, enabled: Boolean): Timer,
    updateTimer(command: String, newCommand: String, newInterval: Int, enabled: Boolean): Timer
  }
  type Timer {
    command: String,
    enabled: Boolean,
    interval: Int
  }