name: "TimedMessages"
main: at.saith.twasi.TimedMessagesPlugin
version: 1.0
description:  "Adds timers to your stream."
author: Saith
dependencies:
  - Commands
  - StreamTracker
commands:
  - timer

permissions:
  - timer.add
  - timer.delete
  - timer.list
  - timer.enable
  - timer.disable
